### ISSUE TITLE
LOGGERS plugin does not take into account loggers configuration for the output file

### ISSUE THREAD

**Issue by 4rtem** [cubewise-code/arc-plugins#26]
Initial configuration in the file:
#MDX Logging
log4j.appender.S_MDX=org.apache.log4j.SharedMemoryAppender
log4j.appender.S_MDX.MemorySize=1 MB
log4j.appender.S_MDX.MaxFileSize=100 MB
log4j.appender.S_MDX.MaxBackupIndex=1
log4j.appender.S_MDX.File=tm1MDX.log
log4j.appender.S_MDX.Format=TM1Event
log4j.appender.S_MDX.TimeZone=GMT

log4j.logger.TM1.Mdx.Interface	=	INFO, S_MDX
log4j.logger.TM1.MdxStatement	=	INFO, S_MDX

After changing logoutput level of Mdx.Interface through the plugin information about S_MDX is lost:
log4j.logger.TM1.Mdx.Interface=DEBUG

**Comment by cubewise-tryan** [comment]
Hi @4rtem,

That is a limitation of the REST API. It only allows updating the default logger unfortunately .
