### ISSUE TITLE
New plugins - Copy cube/dimension name to clipboard

### ISSUE THREAD

**Issue by ppniederbracht** [cubewise-code/arc-plugins#49]
Hi.
I just made it to create my first own plugin and want to share it with the community.
They copy the name of the selected object (cube, dimension, process and chore) to the clipboard which is, I think, very helpfull in some cases.

Hope you enjoy it and it helps you ;-)

Regards Paul
[ls-copy-name.zip](https://github.com/cubewise-code/arc-plugins/files/14583938/ls-copy-name.zip)

**Comment by vviau** [comment]
Hi @ppniederbracht ,

This is awesome!

It would be better if you could fork the repository and then do a merge request so your github account will be associated to this feature.

Cheers,

Vincent

**Comment by vviau** [comment]
Hi @ppniederbracht ,

I would add the following code to be able to copy views and subsets:

`arc.run(['$rootScope', function ($rootScope) {

   $rootScope.plugin("lsCopyCubeName", "Copy", "menu/subsets", {
      icon: "fa-copy",
      description: "This plugin copies the selected name into the clipboard.",
      author: "LS",
      url: "https://github.com/cubewise-code/arc-plugins",
      version: "1.0.0"
   });

}]);

arc.run(['$rootScope', function ($rootScope) {

   $rootScope.plugin("lsCopyCubeName", "Copy", "menu/views", {
      icon: "fa-copy",
      description: "This plugin copies the selected name into the clipboard.",
      author: "LS",
      url: "https://github.com/cubewise-code/arc-plugins",
      version: "1.0.0"
   });

}]);`

**Comment by vviau** [comment]
Hi @ppniederbracht ,

Thanks for the merge request, your plugin is now part to the default plugins.

Thanks a lot for your contribution!

Cheers,

Vincent
